Trait {
	#name : #TMAPheromoneEvents,
	#traits : 'MolComponentEvents',
	#classTraits : 'MolComponentEvents classTrait',
	#category : #'MolAnts-Molecule Contracts'
}

{ #category : #events }
TMAPheromoneEvents >> pheromoneBorn: aPoint [
]

{ #category : #events }
TMAPheromoneEvents >> pheromoneDead: aPoint [
]

{ #category : #events }
TMAPheromoneEvents >> pheromoneReturnBorn: aPoint [
]

{ #category : #events }
TMAPheromoneEvents >> pheromoneReturnDead: aPoint [
]

{ #category : #events }
TMAPheromoneEvents >> pheromoneReturnUpdate: aDictionary [
]

{ #category : #events }
TMAPheromoneEvents >> pheromoneUpdate: aDictionary [
]
