Trait {
	#name : #TMARoleServices,
	#instVars : [
		'roleName'
	],
	#traits : 'MolComponentServices',
	#classTraits : 'MolComponentServices classTrait',
	#category : #'MolAnts-Molecule Contracts'
}

{ #category : #role }
TMARoleServices >> doSimulationStepFor: anAnt [
]

{ #category : #accessing }
TMARoleServices >> getRoleName [

	^ roleName.
]

{ #category : #role }
TMARoleServices >> moveFrom: aPosition [
]
